version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  prod:
    image: rate-my-class
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  dev:
    image: rate-my-class
    volumes:
      - ./app:/app # Mount a volume in the dev mode so we don't have to keep rebuilding the image
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db